import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiCheck,
  HiShieldCheck,
  HiBolt,
  HiUsers,
  HiPhone,
  HiClock,
  HiHeart,
  HiMapPin,
  HiUser,
  HiChatBubbleLeftRight,
  HiInformationCircle,
  HiDocumentText,
  HiShoppingCart,
  HiTag,
  HiBuildingStorefront,
  HiBriefcase,
  HiWallet,
  HiReceiptPercent,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiMotorcycleDuotone,
  PiTargetDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  // New icons for BumiAuto
  check: HiCheck,
  shield: HiShieldCheck,
  bolt: HiBolt,
  users: HiUsers,
  phone: HiPhone,
  clock: HiClock,
  heart: HiHeart,
  mapPin: HiMapPin,
  user: HiUser,
  message: HiChatBubbleLeftRight,
  info: HiInformationCircle,
  fileText: HiDocumentText,
  shoppingCart: HiShoppingCart,
  tag: HiTag,
  store: HiBuildingStorefront,
  briefcase: HiBriefcase,
  wallet: HiWallet,
  percent: HiReceiptPercent,
  bike: PiMotorcycleDuotone,
  target: PiTargetDuotone,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
